rvm:
  - 2.0.0

before_install: wget --no-check-certificate https://dl.bintray.com/mitchellh/packer/0.5.2_linux_amd64.zip && unzip -d packer 0.5.2_linux_amd64.zip
before_script: export PATH=$PATH:$PWD/packer

script: bundle exec rake validate

notifications:
  email:
    recipients:
      - leonard.tavae@gmail.com
      - sysadmin@informatique.gov.pf
    on_success: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/97876495fd4ff628a0b0
    on_success: always
    on_failure: always
    on_start: false
